exclude: ['README.md']
timezone: US/Eastern
markdown: pandoc
#gems:
#  - jekyll-pandoc

collections:
  projects:
    output: true
  papers:
    output: true
#  cv:
#    output: false

deploy: "https://guzmanhe.github.io"

env: github
pandoc:
  format: html5
  extensions:
    - normalize
    - smart
    - mathjax
    - css: ../css/cv.css
    - csl: _styles/acl.csl
    - bibliography: papers/bibtex.bib
